# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       libasyncns
Summary:    Asynchronous Name Service Library
Version:    0.8
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://0pointer.de/lennart/projects/libasyncns
Source0:    http://0pointer.de/lennart/projects/libasyncns/libasyncns-%{version}.tar.gz
Source100:  libasyncns.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
libasyncns is a C library for Linux/Unix for executing name service queries asynchronously. 
It is an asynchronous wrapper around getaddrinfo(3), getnameinfo(3), res_query(3) and 
res_search(3) from libc and libresolv.



%package devel
Summary:    Development components for the libasyncns library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Devel files for the libsyncns.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-rpath

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc README LICENSE
%{_libdir}/libasyncns.so.*
%doc /usr/share/doc/libasyncns
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/asyncns.h
%{_libdir}/libasyncns.so
%{_libdir}/pkgconfig/libasyncns.pc
# << files devel

